# Generated by Django 3.2.6 on 2021-08-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSitePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelSite', models.CharField(max_length=100, verbose_name='Model site that contains this port')),
                ('equipmentModel', models.CharField(max_length=100, verbose_name='BBU model that contains this port')),
                ('equipmentModelSlot', models.CharField(max_length=20, verbose_name='BBU slot that contains this port')),
                ('BoardModel', models.CharField(max_length=20, verbose_name='Board that contains this port')),
                ('port', models.IntegerField(verbose_name='Current port')),
                ('portType', models.CharField(max_length=20, verbose_name='Type of current port')),
            ],
        ),
    ]
